name: Lint and Validate Databricks Code

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black[jupyter] flake8 nbqa
          
      - name: What does nbqa actually see?
        run: python -m nbqa black --diff test_notebook_git.ipynb
        
      - name: Run Black on Notebooks
        run: nbqa black --check test_notebook_git.ipynb
      - name: Run Flake8 on Notebooks
        run: python -m nbqa flake8 test_notebook_git.ipynb --nbqa-md --extend-ignore=E402,F821 --count --statistics
          
