name: Run Databricks Job

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-job:
    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOST: ${{secrets.DATABRICKS_HOST}}
      DATABRICKS_TOKEN: ${{secrets.DATABRICKS_TOKEN}}

    steps:
      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Verify CLI
        run: databricks --version

      - name: Trigger Databricks Job
        run: |
          databricks jobs run-now --job-id 1006369725610440
